ur3e_keyboard_servo:
  ros__parameters:
    command_topic: /servo_node/delta_twist_cmds
    command_type_service: /servo_node/switch_command_type
    frame_id: base_link
    input_backend: terminal
    input_device: ""
    joy_topic: /joy
    joy_deadzone: 0.08
    publish_rate_hz: 100.0
    key_timeout_sec: 0.20
    linear_speed_mps: 0.20
    acceleration_mps2: 0.50
    deceleration_mps2: 0.80
    enable_auto_yaw: false
    auto_yaw_base_frame: base_link
    auto_yaw_tool_frame: tool0
    auto_yaw_gain: 1.5
    max_angular_speed_radps: 0.60
    auto_yaw_min_linear_speed_mps: 0.02
    enable_z: false
    enable_rotation: false
